cmd: check for missing args in public-key
If you don't specify any args to "cosign public-key" right now it fails with

    error: read: . is a directory

which is fairly confusing. So I'm using KeyParseError to indicate there's an
issue with these flags.

Signed-off-by: Ahmet Alp Balkan <ahmetb@google.com>